### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kh-kr** [mgieles/limepy#19]
Hi,

I am trying to install the limepy package using the pip command and method given in the documentation file. 

Below is the error I am getting while installing it using the command line
$ git clone https://github.com/mgieles/limepy.git
$ cd limepy
$ python setup.py install

>(python: can't open file '/home/khushboo/limepy/setup.py': [Errno 2] No such file or directory)

 It seems like the setup.py file is missing.

When I am trying to install it using the pip command, this is what I am getting

> DEPRECATION: Loading egg at /home/khushboo/anaconda3/lib/python3.11/site-packages/astroquery-0.4.7.dev9008-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
> DEPRECATION: Loading egg at /home/khushboo/anaconda3/lib/python3.11/site-packages/fonttools-4.47.2-py3.11-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
> Collecting astro-limepy
>   Using cached astro-limepy-1.2.tar.gz (31 kB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [7 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-install-5deim_0d/astro-limepy_94241b63a7e1448c91d1df2d0a3deab8/setup.py", line 12, in <module>
>           history = io.open('HISTORY.rst').read().replace('.. :changelog:', '')
>                     ^^^^^^^^^^^^^^^^^^^^^^
>       FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

Could you please help me to install it?

Thanks in advance!

Best regards,
Khushboo

**Comment by kh-kr** [comment]
I have successfully installed limepy using the command line given below.

> pip install git+https://github.com/mgieles/limepy

I found this in issue number 6.

Thanks!
